version: '2'

services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data/:/tmp/
      - ./notebooks:/notebooks
      # - /home/zhiwei/Documents/pipeline/notebooks:/notebooks
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      - jupyter 
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=''
      - --no-browser 
      - --NotebookApp.notebook_dir=/notebooks

  minion:
    image: ninai/stimulus-pipeline
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data:/tmp/
      - .:/data/pipeline
    env_file: .env
    entrypoint:
      - python3 
      - /data/pipeline/python/scripts/populate-minion.py

  
  bash:
    image: ninai/pipeline
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data/:/tmp/
      - .:/data/pipeline/
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      - /bin/bash
