version: '2.0'

services:
  notebook:
    image: at-docker.ad.bcm.edu:5000/pipeline:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.st
    ports:
      - "7777:8888"
      # - "7776:8501"
      # - "7775:8503"
    volumes:
      - /mnt/:/mnt/
      - /tmp:/tmp
      - ../../Dropbox/notebooks/pipeline:/data/notebooks
      - .:/data/pipeline/
      - ../stimuli:/data/stimuli
    env_file: .env
    environment:
      - DISPLAY=unix$DISPLAY
    entrypoint:
      - /data/pipeline/personal_pkg.sh
      # - jupyter 
      # - lab
      # - --ip=0.0.0.0
      # - --allow-root
      # - --NotebookApp.token=''
      # - --no-browser


  minion:
    image: at-docker.ad.bcm.edu:5000/pipeline:latest
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data:/tmp/
      - .:/data/pipeline
    env_file: .env
    entrypoint:
      - python3 
      - /data/pipeline/python/scripts/populate-minion.py


#  minion-gpu:
 #   image: ninai/pipeline:tf-gpu
 #   runtime: nvidia
 #   volumes:
 #     - /mnt/:/mnt/
 #     - /home/pipeline_data:/tmp/
 #     - .:/data/pipeline
 #   env_file: .env
 #   entrypoint:
 #     - python3 
 #     - /data/pipeline/python/scripts/populate-minion_gpu.py

  
  bash:
    image: ninai/stimulus-pipeline:latest
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data/:/tmp/
      - .:/data/pipeline
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      - /bin/bash
